name: Sample Orca IaC Scan Workflow
on:
  # Scan for each push event on your protected branch. If you have a different branch configured, please adjust the configuration accordingly by replacing 'main'.
  push:
    branches: [ "main" ]
    paths:
      - '**.tf'
      - '**.json'
      - '**.yml'
      - '**.yaml'
      
  pull_request:
    #branches: [ "main" ]
    paths:
      - '**.tf'
      - '**.json'
      - '**.yml'
      - '**.yaml'
    types: [opened, synchronize, reopened]
    
permissions: 
  actions: read
  contents: read
  checks: write
  issues: write
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  orca-iac_scan:
    name: Orca IaC Scan
    runs-on: ubuntu-latest
    env:
      PROJECT_KEY: default
    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: Run Orca IaC Scan
        uses: orcasecurity/shiftleft-iac-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          path: ./
